import SwiftUI
import AppFactoryKit
import AppFactoryKitRevenueCat

// ─────────────────────────────────────────────────────────────────────────
// VideoCompressor — generated by AppFactoryKit appgen from niche "video-compressor".
// Per-app surface = this config + ContentView's feature. Everything that earns
// (onboarding, paywall, subscriptions, funnel) is inherited from the kit.
// ─────────────────────────────────────────────────────────────────────────

// Paste your RevenueCat public SDK key here to go live. Until then the app runs
// on a mock provider so you can preview the real paywall in the simulator.
private let revenueCatKey = "appl_REPLACE_ME"

@MainActor
enum VideoCompressorFactory {
    static func make() -> AppFactory {
        let provider: PurchaseProvider = revenueCatKey == "appl_REPLACE_ME"
            ? MockPurchaseProvider()
            : RevenueCatPurchaseProvider(apiKey: revenueCatKey, entitlementID: "premium")

        let config = AppFactoryConfiguration(
            appName: "VideoCompressor",
            purchaseProvider: provider,
            onboarding: OnboardingConfiguration(
                slides: [
                    .init(systemImage: "play.rectangle.fill",
                          title: "VideoCompressor",
                          message: "Shrink video size to share/save space."),
                    .init(systemImage: "scissors",
                          title: "Go Pro",
                          message: "No size limit, batch, keep quality, no ads.")
                ],
                presentsPaywallOnFinish: true,
                accent: .purple
            ),
            paywall: PaywallConfiguration(
                headline: "Unlock VideoCompressor Pro",
                subheadline: "No size limit, batch, keep quality, no ads.",
                benefits: [
                    .init(systemImage: "infinity", title: "No size limit"),
                    .init(systemImage: "bolt.fill", title: "Batch"),
                    .init(systemImage: "nosign", title: "Keep quality"),
                    .init(systemImage: "square.and.arrow.up", title: "No ads")
                ],
                productIDs: ["video-compressor_yearly", "video-compressor_weekly"],
                highlightedProductID: "video-compressor_yearly",
                ctaTitle: "Continue",
                dismissButtonDelay: 4,
                isDismissable: true,
                termsURL: URL(string: "https://YOURDOMAIN.com/terms"),
                privacyURL: URL(string: "https://YOURDOMAIN.com/privacy"),
                style: PaywallStyle(accent: .purple, heroSystemImage: "play.rectangle.fill")
            )
        )
        return AppFactory(config)
    }
}

@main
struct VideoCompressorApp: App {
    @StateObject private var factory = VideoCompressorFactory.make()

    var body: some Scene {
        WindowGroup {
            ContentView()
                .appFactoryRoot(factory)
                .tint(.purple)
        }
    }
}
